Repository codesquad-member-2020/airbnb-11, pull requests merged in 2020-06, with the labels that each got.

#90 [BE #89] superhost 여부를 API에서 전달해주도록 변경
  BE/src/main/java/kr/codesquad/airbnb11/common/SQL.kt
  BE/src/main/java/kr/codesquad/airbnb11/controller/response/RoomResponse.java
  BE/src/main/java/kr/codesquad/airbnb11/domain/room/Room.java
  BE/src/main/java/kr/codesquad/airbnb11/domain/room/RoomDAO.java
  BE/src/main/java/kr/codesquad/airbnb11/domain/room/RoomDTO.java
  BE/src/main/java/kr/codesquad/airbnb11/domain/room/RoomRepository.java
  BE/src/test/java/kr/codesquad/airbnb11/controller/RoomRestControllerTest.java
  BE/src/test/java/kr/codesquad/airbnb11/domain/room/RoomRepositoryTest.java
Labels: BE

#91 [BE #46] 페이징 기능 추가
  BE/src/main/java/kr/codesquad/airbnb11/common/SQL.kt
  BE/src/main/java/kr/codesquad/airbnb11/controller/request/SearchRequest.java
  BE/src/main/java/kr/codesquad/airbnb11/controller/response/SearchResponse.java
  BE/src/main/java/kr/codesquad/airbnb11/domain/room/RoomDAO.java
  BE/src/main/java/kr/codesquad/airbnb11/service/RoomService.java
  BE/src/test/java/kr/codesquad/airbnb11/controller/RoomRestControllerTest.java
Labels: BE

#96 [BE] 위도 경도 API 추가
  BE/src/main/java/kr/codesquad/airbnb11/common/SQL.kt
  BE/src/main/java/kr/codesquad/airbnb11/controller/response/RoomResponse.java
  BE/src/main/java/kr/codesquad/airbnb11/domain/room/Room.java
  BE/src/main/java/kr/codesquad/airbnb11/domain/room/RoomDAO.java
  BE/src/main/java/kr/codesquad/airbnb11/domain/room/RoomDTO.java
Labels: BE

#97 [Deploy] 2020-06-01
  BE/src/main/java/kr/codesquad/airbnb11/common/SQL.kt
  BE/src/main/java/kr/codesquad/airbnb11/common/config/WebConfig.java
  BE/src/main/java/kr/codesquad/airbnb11/controller/RoomRestController.java
  BE/src/main/java/kr/codesquad/airbnb11/controller/request/ReservationRequest.java
  BE/src/main/java/kr/codesquad/airbnb11/controller/request/SearchRequest.java
  BE/src/main/java/kr/codesquad/airbnb11/controller/response/RoomResponse.java
  BE/src/main/java/kr/codesquad/airbnb11/controller/response/SearchResponse.java
  BE/src/main/java/kr/codesquad/airbnb11/domain/reservation/Reservation.java
  BE/src/main/java/kr/codesquad/airbnb11/domain/reservation/ReservationRepository.java
  BE/src/main/java/kr/codesquad/airbnb11/domain/room/Room.java
  BE/src/main/java/kr/codesquad/airbnb11/domain/room/RoomDAO.java
  BE/src/main/java/kr/codesquad/airbnb11/domain/room/RoomDTO.java
  BE/src/main/java/kr/codesquad/airbnb11/domain/room/RoomRepository.java
  BE/src/main/java/kr/codesquad/airbnb11/service/RoomService.java
  BE/src/main/resources/db/migration/V1.0.0__schema_init.sql
  BE/src/test/java/kr/codesquad/airbnb11/Airbnb11ApplicationTests.java
  BE/src/test/java/kr/codesquad/airbnb11/controller/RoomRestControllerTest.java
  BE/src/test/java/kr/codesquad/airbnb11/domain/room/RoomRepositoryTest.java
Labels: BE

#98 [BE] feat : swagger 설정 추가
  BE/src/main/java/kr/codesquad/airbnb11/common/config/SpringFoxConfig.java
  BE/src/main/java/kr/codesquad/airbnb11/controller/LoginController.java
  BE/src/main/java/kr/codesquad/airbnb11/controller/RoomRestController.java
Labels: BE

#100 [Deploy] Phase2 마무리 배포
  BE/src/main/java/kr/codesquad/airbnb11/common/config/SpringFoxConfig.java
  BE/src/main/java/kr/codesquad/airbnb11/controller/LoginController.java
  BE/src/main/java/kr/codesquad/airbnb11/controller/RoomRestController.java
Labels: BE

#105 [BE #47] 방 정보 상세보기 API를 추가합니다.
  BE/src/main/java/kr/codesquad/airbnb11/common/SQL.kt
  BE/src/main/java/kr/codesquad/airbnb11/controller/RoomRestController.java
  BE/src/main/java/kr/codesquad/airbnb11/controller/request/RoomDetailRequest.java
  BE/src/main/java/kr/codesquad/airbnb11/controller/response/RoomDetailResponse.java
  BE/src/main/java/kr/codesquad/airbnb11/domain/room/Room.java
  BE/src/main/java/kr/codesquad/airbnb11/domain/room/RoomDAO.java
  BE/src/main/java/kr/codesquad/airbnb11/domain/room/RoomDTO.java
  BE/src/main/java/kr/codesquad/airbnb11/service/RoomService.java
  BE/src/main/resources/db/migration/V1.0.0__schema_init.sql
  BE/src/main/resources/db/migration/V1.0.1__mock_data_init.sql
Labels: BE

#109 지도 기능 추가 및 Service API 연동
  FE/package-lock.json
  FE/package.json
  FE/public/index.html
  FE/src/components/Common/GuestButton/GuestButton.jsx
  FE/src/components/Main/BGImage/BGImage.jsx
  FE/src/components/Main/Main.jsx
  FE/src/components/Main/SearchNavigation/SearchNavigation.jsx
  FE/src/components/ReservationModal/ReservationModal.jsx
  FE/src/components/SearchResult/AccomodationCard/AccomodationCard.jsx
  FE/src/components/SearchResult/Caution/Caution.jsx
  FE/src/components/SearchResult/Header/Header.jsx
  FE/src/components/SearchResult/Map/AccomodationInfo/AccomodationInfo.jsx
  FE/src/components/SearchResult/Map/Map.jsx
  FE/src/components/SearchResult/SearchResult.jsx
  FE/src/mockData/searchResult.js
  FE/webpack.common.js
  FE/webpack.config.js
  FE/webpack.development.js
  FE/webpack.production.js
Labels: FE

#108 [BE #106] Reservation API 개발
  BE/src/main/java/kr/codesquad/airbnb11/controller/ReservationRestController.java
  BE/src/main/java/kr/codesquad/airbnb11/controller/request/CancelReservationRequest.java
  BE/src/main/java/kr/codesquad/airbnb11/domain/reservation/ReservationRepository.java
  BE/src/main/java/kr/codesquad/airbnb11/service/ReservationService.java
Labels: BE

#110 하드코딩 되어있던 부분을 수정, 불필요한 console.log 문 삭제
  FE/src/components/Main/BGImage/BGImage.jsx
  FE/src/components/Main/Header/Header.jsx
  FE/src/components/Main/Header/HeaderNavigation/HeaderNavigation.jsx
  FE/src/components/SearchResult/Header/Header.jsx
  FE/src/components/SearchResult/Header/HeaderNavigation/HeaderNavigation.jsx
  FE/src/components/SearchResult/SearchResult.jsx
  FE/src/utils/calcDateDiff.js
  FE/webpack.config.js
Labels: FE

#111 jwt token 확인 코드 추가
  FE/package-lock.json
  FE/package.json
  FE/src/components/Main/Main.jsx
Labels: FE

#114 [BE #64] chore: zip파일을 만들지 않고 Code Deploy push를 활용
  .github/workflows/gradle-cd.yml
Labels: BE

#115 [Deploy] 2020-06-03
  .github/workflows/gradle-cd.yml
  BE/src/main/java/kr/codesquad/airbnb11/common/SQL.kt
  BE/src/main/java/kr/codesquad/airbnb11/controller/ReservationRestController.java
  BE/src/main/java/kr/codesquad/airbnb11/controller/RoomRestController.java
  BE/src/main/java/kr/codesquad/airbnb11/controller/request/CancelReservationRequest.java
  BE/src/main/java/kr/codesquad/airbnb11/controller/request/RoomDetailRequest.java
  BE/src/main/java/kr/codesquad/airbnb11/controller/response/RoomDetailResponse.java
  BE/src/main/java/kr/codesquad/airbnb11/controller/response/RoomResponse.java
  BE/src/main/java/kr/codesquad/airbnb11/domain/reservation/ReservationRepository.java
  BE/src/main/java/kr/codesquad/airbnb11/domain/review/Review.java
  BE/src/main/java/kr/codesquad/airbnb11/domain/review/ReviewRepository.java
  BE/src/main/java/kr/codesquad/airbnb11/domain/room/Room.java
  BE/src/main/java/kr/codesquad/airbnb11/domain/room/RoomDAO.java
  BE/src/main/java/kr/codesquad/airbnb11/domain/room/RoomDTO.java
  BE/src/main/java/kr/codesquad/airbnb11/domain/user/User.java
  BE/src/main/java/kr/codesquad/airbnb11/service/ReservationService.java
  BE/src/main/java/kr/codesquad/airbnb11/service/RoomService.java
  BE/src/main/resources/db/migration/V1.0.0__schema_init.sql
  BE/src/main/resources/db/migration/V1.0.1__mock_data_init.sql
  BE/src/test/resources/schema.sql
Labels: BE

#116 [BE] chore: ci가 동작하지 않아서 수정
  .github/workflows/gradle-ci.yml
Labels: BE

#117 [BE] CI 스크립트 수정
  .github/workflows/gradle-ci.yml
Labels: BE

#113 [BE #40] mock data 추가
  BE/src/main/resources/db/migration/V1.0.0__schema_init.sql
  BE/src/main/resources/db/migration/V1.0.4__add_mock_data.sql
  BE/src/test/java/kr/codesquad/airbnb11/domain/room/RoomDTOTest.java
Labels: BE

#118 [FE #76] FE CI 적용
  .github/workflows/nodejs-cd.yml
  .github/workflows/nodejs-ci.yml
  FE/appspec.yml
  FE/deploy.sh
Labels: BE, FE

#112 [BE #58] 근처 방 조회 기능을 구현합니다.
  BE/src/main/java/kr/codesquad/airbnb11/common/SQL.kt
  BE/src/main/java/kr/codesquad/airbnb11/controller/RoomRestController.java
  BE/src/main/java/kr/codesquad/airbnb11/controller/request/SearchRequest.java
  BE/src/main/java/kr/codesquad/airbnb11/controller/response/RoomResponse.java
  BE/src/main/java/kr/codesquad/airbnb11/domain/room/Room.java
  BE/src/main/java/kr/codesquad/airbnb11/domain/room/RoomDAO.java
  BE/src/main/java/kr/codesquad/airbnb11/domain/room/RoomDTO.java
  BE/src/main/java/kr/codesquad/airbnb11/service/RoomService.java
  BE/src/main/resources/db/migration/V1.0.0__schema_init.sql
  BE/src/main/resources/db/migration/V1.0.1__mock_data_init.sql
  BE/src/main/resources/db/migration/V1.0.5__add_spatial_index.sql
  BE/src/main/resources/db/migration/V1.0.6__add_stored_procedure.sql
  BE/src/test/java/kr/codesquad/airbnb11/controller/RoomRestControllerTest.java
Labels: BE

#119 [Deploy] 2020-06-04
  BE/src/main/java/kr/codesquad/airbnb11/common/SQL.kt
  BE/src/main/java/kr/codesquad/airbnb11/controller/RoomRestController.java
  BE/src/main/java/kr/codesquad/airbnb11/controller/request/SearchRequest.java
  BE/src/main/java/kr/codesquad/airbnb11/controller/response/RoomResponse.java
  BE/src/main/java/kr/codesquad/airbnb11/domain/room/Room.java
  BE/src/main/java/kr/codesquad/airbnb11/domain/room/RoomDAO.java
  BE/src/main/java/kr/codesquad/airbnb11/domain/room/RoomDTO.java
  BE/src/main/java/kr/codesquad/airbnb11/service/RoomService.java
  BE/src/main/resources/db/migration/V1.0.0__schema_init.sql
  BE/src/main/resources/db/migration/V1.0.1__mock_data_init.sql
  BE/src/main/resources/db/migration/V1.0.4__add_mock_data.sql
  BE/src/main/resources/db/migration/V1.0.5__add_spatial_index.sql
  BE/src/main/resources/db/migration/V1.0.6__add_stored_procedure.sql
  BE/src/test/java/kr/codesquad/airbnb11/controller/RoomRestControllerTest.java
  BE/src/test/java/kr/codesquad/airbnb11/domain/room/RoomDTOTest.java
Labels: BE

#120 rating, 환경변수 추가
  FE/.env.development
  FE/.env.production
  FE/.gitignore
  FE/src/components/SearchResult/AccomodationCard/AccomodationCard.jsx
  FE/src/components/SearchResult/Caution/Caution.jsx
  FE/src/components/SearchResult/Map/CloseButton/CloseButton.jsx
  FE/src/components/SearchResult/Map/Map.jsx
  FE/src/components/SearchResult/SearchResult.jsx
Labels: FE

#121 [FE] chore: dev, prod 명령어 분리
  FE/package.json
Labels: FE

#122 chore: 빌드 옵션 수정
  .github/workflows/nodejs-cd.yml
Labels: BE, FE

#123 [BE] refactor: 전체 가격을 반환하도록 수정
  BE/src/main/java/kr/codesquad/airbnb11/common/SQL.kt
  BE/src/main/java/kr/codesquad/airbnb11/controller/response/SearchResponse.java
  BE/src/main/java/kr/codesquad/airbnb11/domain/room/RoomDAO.java
  BE/src/main/java/kr/codesquad/airbnb11/service/RoomService.java
Labels: BE

#125 [FE] 지도 기능 개발
  FE/src/components/Common/GuestButton/GuestButton.jsx
  FE/src/components/Main/SearchNavigation/SearchNavigation.jsx
  FE/src/components/SearchResult/AccomodationCard/AccomodationCard.jsx
  FE/src/components/SearchResult/Header/Header.jsx
  FE/src/components/SearchResult/IconTextButton/IconTextButton.jsx
  FE/src/components/SearchResult/Map/Map.jsx
  FE/src/components/SearchResult/SearchResult.jsx
  FE/src/statement/actionNames/guest/guestActionName.js
  FE/src/statement/reducers/guest/guestCountReducer.js
  FE/src/statement/reducers/rootReducer.js
Labels: FE

#124 [BE #40] mock data 수정
  BE/src/main/resources/db/migration/V1.0.0__schema_init.sql
  BE/src/main/resources/db/migration/V1.0.4__add_mock_data.sql
Labels: BE

#126 [Deploy] 가격정보 업데이트, 위도 경도 데이터 변경, 데이터 추가로 더 추가
  BE/src/main/java/kr/codesquad/airbnb11/common/SQL.kt
  BE/src/main/java/kr/codesquad/airbnb11/controller/response/SearchResponse.java
  BE/src/main/java/kr/codesquad/airbnb11/domain/room/RoomDAO.java
  BE/src/main/java/kr/codesquad/airbnb11/service/RoomService.java
  BE/src/main/resources/db/migration/V1.0.0__schema_init.sql
  BE/src/main/resources/db/migration/V1.0.4__add_mock_data.sql
Labels: BE

#127 [FE] marker 클릭 시 호텔 정보 표시하는 기능 추가
  FE/src/components/Common/GuestButton/GuestButton.jsx
  FE/src/components/SearchResult/AccomodationCard/AccomodationCard.jsx
  FE/src/components/SearchResult/Map/AccomodationInfo/AccomodationInfo.jsx
  FE/src/components/SearchResult/Map/Map.jsx
  FE/src/components/SearchResult/SearchResult.jsx
Labels: FE

#129 [FE] feat: 지도 근처 숙소 출력 기능 추가
  FE/.env.development
  FE/.env.production
  FE/src/components/SearchResult/Map/AccomodationInfo/AccomodationInfo.jsx
  FE/src/components/SearchResult/Map/Map.jsx
  FE/src/components/SearchResult/SearchResult.jsx
Labels: FE

#130 [FE #107] 맵 중앙 좌표 조정
  FE/src/components/SearchResult/SearchResult.jsx
Labels: FE

#128 [BE #99] Interceptor
  BE/src/main/java/kr/codesquad/airbnb11/common/config/IntercepterConfig.java
  BE/src/main/java/kr/codesquad/airbnb11/common/security/ReservationInterceptor.java
  BE/src/main/java/kr/codesquad/airbnb11/service/LoginService.java
  BE/src/main/resources/application.yml
  BE/src/test/java/kr/codesquad/airbnb11/controller/RoomRestControllerTest.java
  BE/src/test/resources/application.yml
Labels: BE

#131 [Deploy] 2020-06-04
  BE/src/main/java/kr/codesquad/airbnb11/common/config/IntercepterConfig.java
  BE/src/main/java/kr/codesquad/airbnb11/common/security/ReservationInterceptor.java
  BE/src/main/java/kr/codesquad/airbnb11/service/LoginService.java
  BE/src/main/resources/application.yml
  BE/src/test/java/kr/codesquad/airbnb11/controller/RoomRestControllerTest.java
  BE/src/test/resources/application.yml
Labels: BE

#133 [FE] modify: 예약 모달 수정
  FE/src/components/ReservationModal/ChargeDetails/ChargeDetails.jsx
  FE/src/components/ReservationModal/ReservationModal.jsx
  FE/src/components/SearchResult/Map/AccomodationInfo/AccomodationInfo.jsx
  FE/src/components/SearchResult/SearchResult.jsx
  FE/src/routers/SearchResultRouter.jsx
Labels: FE

#134 [FE] 테스트 코드 제거
  FE/src/components/Main/Header/Header.jsx
Labels: FE

#135 [BE] refactor: 검색범위 확장
  BE/src/main/resources/db/migration/V1.0.6__add_stored_procedure.sql
Labels: BE

#136 [Deploy] 검색범위 확장
  BE/src/main/resources/db/migration/V1.0.6__add_stored_procedure.sql
Labels: BE

#137 [BE] refactor: 검색결과 추가
  BE/src/main/resources/db/migration/V1.0.6__add_stored_procedure.sql
Labels: BE

#138 [Deploy]
  BE/src/main/resources/db/migration/V1.0.6__add_stored_procedure.sql
Labels: BE
