Repository codesquad-member-2020/airbnb-11, pull requests merged in 2020-05, with the labels that each got.

#11 [BE #8] spring project initialize
  BE/.gitignore
  BE/build.gradle
  BE/gradle/wrapper/gradle-wrapper.jar
  BE/gradle/wrapper/gradle-wrapper.properties
  BE/gradlew
  BE/gradlew.bat
  BE/settings.gradle
  BE/src/main/java/kr/codesquad/airbnb11/Airbnb11Application.java
  BE/src/main/resources/application.properties
  BE/src/test/java/kr/codesquad/airbnb11/Airbnb11ApplicationTests.java
Labels: BE

#15 [BE #7] Mock API를 구현했습니다!
  BE/src/main/java/kr/codesquad/airbnb11/Airbnb11Application.java
  BE/src/main/java/kr/codesquad/airbnb11/controller/RoomRestController.java
  BE/src/main/java/kr/codesquad/airbnb11/controller/request/SearchRequest.java
  BE/src/main/java/kr/codesquad/airbnb11/controller/response/RoomResponse.java
  BE/src/main/java/kr/codesquad/airbnb11/controller/response/SearchResponse.java
  BE/src/main/resources/application.yml
  BE/src/main/resources/data.sql
  BE/src/main/resources/schema.sql
Labels: BE

#22 [BE #21] feat: 에러 응답 객체 구현
  BE/src/main/java/kr/codesquad/airbnb11/common/error/ErrorCode.java
  BE/src/main/java/kr/codesquad/airbnb11/common/error/ErrorResponse.java
  BE/src/main/java/kr/codesquad/airbnb11/common/error/GlobalRestExceptionHandler.java
  BE/src/main/java/kr/codesquad/airbnb11/common/error/exception/BusinessException.java
  BE/src/main/java/kr/codesquad/airbnb11/common/error/exception/EntityNotFoundException.java
  BE/src/main/java/kr/codesquad/airbnb11/common/error/exception/LoginRequiredException.java
  BE/src/main/java/kr/codesquad/airbnb11/common/error/exception/UserNotFoundException.java
Labels: BE

#24 [BE #23] flyway 설정 추가 및 schema init, mock data 추가 sql 작성
  BE/build.gradle
  BE/src/main/resources/application.yml
  BE/src/main/resources/data.sql
  BE/src/main/resources/db/migration/V1.0.0__schema_init.sql
  BE/src/main/resources/db/migration/V1.0.1__mock_data_init.sql
  BE/src/main/resources/flyway.conf
Labels: BE, enhancement

#27 [BE #26] chore : prod profile 추가
  BE/src/main/resources/application.yml
Labels: BE

#28 Phase 1 dev Pull request
  BE/.gitignore
  BE/build.gradle
  BE/gradle/wrapper/gradle-wrapper.jar
  BE/gradle/wrapper/gradle-wrapper.properties
  BE/gradlew
  BE/gradlew.bat
  BE/settings.gradle
  BE/src/main/java/kr/codesquad/airbnb11/Airbnb11Application.java
  BE/src/main/java/kr/codesquad/airbnb11/common/error/ErrorCode.java
  BE/src/main/java/kr/codesquad/airbnb11/common/error/ErrorResponse.java
  BE/src/main/java/kr/codesquad/airbnb11/common/error/GlobalRestExceptionHandler.java
  BE/src/main/java/kr/codesquad/airbnb11/common/error/exception/BusinessException.java
  BE/src/main/java/kr/codesquad/airbnb11/common/error/exception/EntityNotFoundException.java
  BE/src/main/java/kr/codesquad/airbnb11/common/error/exception/LoginRequiredException.java
  BE/src/main/java/kr/codesquad/airbnb11/common/error/exception/UserNotFoundException.java
  BE/src/main/java/kr/codesquad/airbnb11/controller/RoomRestController.java
  BE/src/main/java/kr/codesquad/airbnb11/controller/request/SearchRequest.java
  BE/src/main/java/kr/codesquad/airbnb11/controller/response/RoomResponse.java
  BE/src/main/java/kr/codesquad/airbnb11/controller/response/SearchResponse.java
  BE/src/main/resources/application.yml
  BE/src/main/resources/db/migration/V1.0.0__schema_init.sql
  BE/src/main/resources/db/migration/V1.0.1__mock_data_init.sql
  BE/src/main/resources/flyway.conf
  BE/src/test/java/kr/codesquad/airbnb11/Airbnb11ApplicationTests.java
Labels: BE

#30 [BE #29] Room Domain 클래스를 생성합니다.
  BE/src/main/java/kr/codesquad/airbnb11/controller/RoomRestController.java
  BE/src/main/java/kr/codesquad/airbnb11/domain/dummy
  BE/src/main/java/kr/codesquad/airbnb11/domain/room/Room.java
  BE/src/main/java/kr/codesquad/airbnb11/domain/room/RoomRepository.java
  BE/src/main/java/kr/codesquad/airbnb11/service/dummy
Labels: BE

#32 [BE #29] chore : room mock data 추가
  BE/src/main/resources/db/migration/V1.0.1__mock_data_init.sql
  README.md
Labels: BE

#31 [BE #29] feat : Api결과를 감쌀 result 객체 생성
  BE/src/main/java/kr/codesquad/airbnb11/common/error/ApiError.java
  BE/src/main/java/kr/codesquad/airbnb11/common/error/ApiResult.java
  BE/src/main/java/kr/codesquad/airbnb11/common/error/GlobalRestExceptionHandler.java
Labels: BE

#33 Feature/be/review domain
  BE/src/main/java/kr/codesquad/airbnb11/domain/review/Review.java
  BE/src/main/java/kr/codesquad/airbnb11/domain/review/ReviewRepository.java
Labels: BE

#36 [BE #35] 스프링 설정을 추가합니다.
  BE/src/main/java/kr/codesquad/airbnb11/common/config/JacksonConfig.java
  BE/src/main/java/kr/codesquad/airbnb11/common/config/SpringFoxConfig.java
  BE/src/main/java/kr/codesquad/airbnb11/common/config/WebConfig.java
  BE/src/test/java/kr/codesquad/airbnb11/Airbnb11ApplicationTests.java
Labels: BE

#37 [BE #6]: feat: github 자동배포 설정
  BE/.github/workflows/gradle.yml
  BE/appspec.yml
  BE/deploy.sh
Labels: BE

#38 Phase 1 pull requset
  BE/.github/workflows/gradle.yml
  BE/appspec.yml
  BE/deploy.sh
  BE/src/main/java/kr/codesquad/airbnb11/common/config/JacksonConfig.java
  BE/src/main/java/kr/codesquad/airbnb11/common/config/SpringFoxConfig.java
  BE/src/main/java/kr/codesquad/airbnb11/common/config/WebConfig.java
  BE/src/main/java/kr/codesquad/airbnb11/common/error/ApiError.java
  BE/src/main/java/kr/codesquad/airbnb11/common/error/ApiResult.java
  BE/src/main/java/kr/codesquad/airbnb11/common/error/GlobalRestExceptionHandler.java
  BE/src/main/java/kr/codesquad/airbnb11/controller/RoomRestController.java
  BE/src/main/java/kr/codesquad/airbnb11/domain/dummy
  BE/src/main/java/kr/codesquad/airbnb11/domain/review/Review.java
  BE/src/main/java/kr/codesquad/airbnb11/domain/review/ReviewRepository.java
  BE/src/main/java/kr/codesquad/airbnb11/domain/room/Room.java
  BE/src/main/java/kr/codesquad/airbnb11/domain/room/RoomRepository.java
  BE/src/main/java/kr/codesquad/airbnb11/service/dummy
  BE/src/main/resources/db/migration/V1.0.1__mock_data_init.sql
  BE/src/test/java/kr/codesquad/airbnb11/Airbnb11ApplicationTests.java
  README.md
Labels: BE

#42 [FE #1] 개발환경 구축
  FE/.babelrc
  FE/.gitignore
  FE/lib/style/reset.css
  FE/package-lock.json
  FE/package.json
  FE/public/index.html
  FE/src/App.css
  FE/src/App.jsx
  FE/src/index.jsx
  FE/webpack.config.js
Labels: FE

#41 [BE #6] fix: auto-deploy를 위한 workflow 경로가 잘못되어 수정
  .github/workflows/gradle-cd.yml
  .github/workflows/gradle-ci.yml
  BE/build.gradle
  BE/deploy.sh
  BE/src/main/resources/application.yml
  BE/src/test/resources/application.yml
Labels: BE, bug

#52 [BE #6] fix: 배포가 제대로 되지 않아서 로그를 남기도록 수정
  BE/deploy.sh
Labels: BE

#53 [BE #6] fix: 배포경로 수정
  BE/deploy.sh
Labels: BE, bug

#54 [BE #6] fix: 잘 도는지 확인하기 위해서 추가했던 로깅을 제거
  BE/deploy.sh
Labels: BE, bug

#55 [FE #3] 스켈레톤 코드 작성
  FE/package-lock.json
  FE/src/App.css
  FE/src/App.jsx
  FE/src/actions/allActions.js
  FE/src/actions/charge/chargeAction.js
  FE/src/actions/date/dateAction.js
  FE/src/actions/guest/adultCountAction.js
  FE/src/actions/guest/childrenCountAction.js
  FE/src/actions/guest/infantsCountAction.js
  FE/src/components/Main/Header/Header.jsx
  FE/src/components/Main/Header/Logo/Logo.jsx
  FE/src/components/Main/Header/RadiusTextButton/RadiusTextButton.jsx
  FE/src/components/Main/Header/TextButton/TextButton.jsx
  FE/src/components/Main/Main.jsx
  FE/src/components/Main/SearchNavigation/ChargeButton/ChargeButton.jsx
  FE/src/components/Main/SearchNavigation/DateButton/DateButton.jsx
  FE/src/components/Main/SearchNavigation/GuestButton/GuestButton.jsx
  FE/src/components/Main/SearchNavigation/SearchButton/SearchButton.jsx
  FE/src/components/Main/SearchNavigation/SearchNavigation.jsx
  FE/src/components/ReservationModal/ChargeDetails/ChargeDetails.jsx
  FE/src/components/ReservationModal/ChargePerDay/ChargePerDay.jsx
  FE/src/components/ReservationModal/CheckInOutDate/CheckInOutDate.jsx
  FE/src/components/ReservationModal/GuestCount/GuestCount.jsx
  FE/src/components/ReservationModal/Rating/Rating.jsx
  FE/src/components/ReservationModal/ReservationModal.jsx
  FE/src/components/SearchResult/AccomodationCard/AccomodationCard.jsx
  FE/src/components/SearchResult/Caution/Caution.jsx
  FE/src/components/SearchResult/CurrentPageIndicator/CurrentPageIndicator.jsx
  FE/src/components/SearchResult/CurrentPageIndicator/PageNumberButton/PageNumberButton.jsx
  FE/src/components/SearchResult/CurrentPageIndicator/PageSkipButton/PageSkipButton.jsx
  FE/src/components/SearchResult/SearchResult.jsx
  FE/src/constants/charge.js
  FE/src/constants/guest.js
  FE/src/index.jsx
  FE/src/reducers/charge/chargeReducer.js
  FE/src/reducers/date/dateReducer.js
  FE/src/reducers/guest/adultCountReducer.js
  FE/src/reducers/guest/childrenCountReducer.js
  FE/src/reducers/guest/infantsCountReducer.js
  FE/src/reducers/rootReducer.js
  FE/src/routers/AppRouter.jsx
  FE/src/utils/fetchRequest.js
Labels: FE

#51 Feature/be/spring actuator
  BE/build.gradle
  BE/src/main/resources/application.yml
Labels: BE

#56 [BE] Phase 1 내용을 병합합니다.
  BE/build.gradle
  BE/src/main/resources/application.yml
Labels: BE

#57 [BE #25]: refactor: DB에 location 컬럼 추가
  BE/flyway.conf
  BE/src/main/resources/db/migration/V1.0.0__schema_init.sql
  BE/src/main/resources/db/migration/V1.0.1__mock_data_init.sql
Labels: BE

#61 Feature/be/swagger config
  BE/src/main/java/kr/codesquad/airbnb11/common/config/SpringFoxConfig.java
  BE/src/main/java/kr/codesquad/airbnb11/controller/RoomRestController.java
  BE/src/main/java/kr/codesquad/airbnb11/controller/request/SearchRequest.java
  BE/src/main/resources/application.yml
Labels: BE

#59 Feature/be/room people count
  BE/src/main/java/kr/codesquad/airbnb11/domain/room/Room.java
  BE/src/main/java/kr/codesquad/airbnb11/domain/room/RoomRepository.java
  BE/src/main/resources/application.yml
  BE/src/test/java/kr/codesquad/airbnb11/domain/room/RoomRepositoryTest.java
  BE/src/test/resources/application.yml
  BE/src/test/resources/schema.sql
Labels: BE

#65 Feature/be/phase1 review
  .github/workflows/gradle-cd.yml
  .github/workflows/gradle-ci.yml
  BE/deploy.sh
  BE/src/main/java/kr/codesquad/airbnb11/common/error/GlobalRestExceptionHandler.java
  BE/src/test/java/kr/codesquad/airbnb11/domain/room/RoomRepositoryTest.java
  BE/src/test/resources/application.yml
Labels: BE

#67 [BE #62] refactor: reservation Table 변경
  BE/src/main/resources/db/migration/V1.0.0__schema_init.sql
Labels: BE

#66 [BE #45] 요금 검색기능 추가
  BE/src/main/java/kr/codesquad/airbnb11/domain/dummy
  BE/src/main/java/kr/codesquad/airbnb11/domain/room/RoomDTO.java
  BE/src/main/java/kr/codesquad/airbnb11/domain/room/RoomRepository.java
  BE/src/main/resources/db/migration/V1.0.2__add_price_index.sql
  BE/src/test/java/kr/codesquad/airbnb11/domain/room/RoomDTOTest.java
  BE/src/test/java/kr/codesquad/airbnb11/domain/room/RoomRepositoryTest.java
Labels: BE

#70 [Deploy] 2020-05-28
  .github/workflows/gradle-cd.yml
  .github/workflows/gradle-ci.yml
  BE/deploy.sh
  BE/flyway.conf
  BE/src/main/java/kr/codesquad/airbnb11/common/config/SpringFoxConfig.java
  BE/src/main/java/kr/codesquad/airbnb11/common/error/GlobalRestExceptionHandler.java
  BE/src/main/java/kr/codesquad/airbnb11/controller/RoomRestController.java
  BE/src/main/java/kr/codesquad/airbnb11/controller/request/SearchRequest.java
  BE/src/main/java/kr/codesquad/airbnb11/domain/dummy
  BE/src/main/java/kr/codesquad/airbnb11/domain/room/Room.java
  BE/src/main/java/kr/codesquad/airbnb11/domain/room/RoomDTO.java
  BE/src/main/java/kr/codesquad/airbnb11/domain/room/RoomRepository.java
  BE/src/main/resources/application.yml
  BE/src/main/resources/db/migration/V1.0.0__schema_init.sql
  BE/src/main/resources/db/migration/V1.0.1__mock_data_init.sql
  BE/src/main/resources/db/migration/V1.0.2__add_price_index.sql
  BE/src/test/java/kr/codesquad/airbnb11/domain/room/RoomDTOTest.java
  BE/src/test/java/kr/codesquad/airbnb11/domain/room/RoomRepositoryTest.java
  BE/src/test/resources/application.yml
  BE/src/test/resources/schema.sql
Labels: BE

#71 [BE #45] feat: BigMoneyConverter 개발
  BE/src/main/java/kr/codesquad/airbnb11/common/utils/BigMoneyConverter.java
  BE/src/main/java/kr/codesquad/airbnb11/domain/room/RoomDTO.java
  BE/src/test/java/kr/codesquad/airbnb11/common/utils/BigMoneyConverterTest.java
  BE/src/test/java/kr/codesquad/airbnb11/domain/room/RoomDTOTest.java
Labels: BE

#72 [FE #18] MainPage 개발
  FE/lib/style/reset.css
  FE/package-lock.json
  FE/package.json
  FE/src/App.jsx
  FE/src/actions/guest/adultCountAction.js
  FE/src/actions/guest/childrenCountAction.js
  FE/src/actions/guest/infantsCountAction.js
  FE/src/components/Main/Header/Header.jsx
  FE/src/components/Main/Header/HeaderNavigation/HeaderNavigation.jsx
  FE/src/components/Main/Header/HeaderNavigation/RadiusTextButton/RadiusTextButton.jsx
  FE/src/components/Main/Header/HeaderNavigation/TextButton/TextButton.jsx
  FE/src/components/Main/Header/Logo/Logo.jsx
  FE/src/components/Main/Header/RadiusTextButton/RadiusTextButton.jsx
  FE/src/components/Main/Header/TextButton/TextButton.jsx
  FE/src/components/Main/Main.jsx
  FE/src/components/Main/SearchNavigation/CommonComponent/SearchNaviButton.jsx
  FE/src/components/Main/SearchNavigation/DateButton/DateButton.jsx
  FE/src/components/Main/SearchNavigation/GuestButton/GuestButton.jsx
  FE/src/components/Main/SearchNavigation/SearchButton/SearchButton.jsx
  FE/src/components/Main/SearchNavigation/SearchNavigation.jsx
  FE/src/constants/mainpage.js
  FE/src/index.jsx
  FE/src/reducers/charge/chargeReducer.js
  FE/src/reducers/date/dateReducer.js
  FE/src/reducers/guest/adultCountReducer.js
  FE/src/reducers/guest/childrenCountReducer.js
  FE/src/reducers/guest/infantsCountReducer.js
  FE/src/reducers/rootReducer.js
  FE/src/statement/actions/allActions.js
  FE/src/statement/actions/charge/chargeAction.js
  FE/src/statement/actions/date/dateAction.js
  FE/src/statement/actions/focusIdAction.js
  FE/src/statement/actions/guest/adultCountAction.js
  FE/src/statement/actions/guest/childrenCountAction.js
  FE/src/statement/actions/guest/infantsCountAction.js
  FE/src/statement/constants/date/dateActionName.js
  FE/src/statement/constants/focusIdActionName.js
  FE/src/statement/constants/guest/adultActionName.js
  FE/src/statement/constants/guest/childrenActionName.js
  FE/src/statement/constants/guest/infantsActionName.js
  FE/src/statement/reducers/charge/chargeReducer.js
  FE/src/statement/reducers/date/dateReducer.js
  FE/src/statement/reducers/focusIdReducer.js
  FE/src/statement/reducers/guest/adultCountReducer.js
  FE/src/statement/reducers/guest/childrenCountReducer.js
  FE/src/statement/reducers/guest/infantsCountReducer.js
  FE/src/statement/reducers/rootReducer.js
  FE/webpack.config.js
Labels: FE

#69 [BE] login oauth
  BE/src/main/java/kr/codesquad/airbnb11/common/config/WebConfig.java
  BE/src/main/java/kr/codesquad/airbnb11/common/security/GithubKey.java
  BE/src/main/java/kr/codesquad/airbnb11/common/security/GithubPayload.java
  BE/src/main/java/kr/codesquad/airbnb11/common/security/GithubToken.java
  BE/src/main/java/kr/codesquad/airbnb11/common/security/GithubUser.java
  BE/src/main/java/kr/codesquad/airbnb11/controller/LoginController.java
  BE/src/main/java/kr/codesquad/airbnb11/domain/user/User.java
  BE/src/main/java/kr/codesquad/airbnb11/domain/user/UserDTO.java
  BE/src/main/java/kr/codesquad/airbnb11/domain/user/UserRepository.java
  BE/src/main/java/kr/codesquad/airbnb11/service/JwtService.java
  BE/src/main/java/kr/codesquad/airbnb11/service/LoginService.java
  BE/src/main/java/kr/codesquad/airbnb11/service/OAuthService.java
  BE/src/main/java/kr/codesquad/airbnb11/service/dummy
  BE/src/main/resources/application.yml
  BE/src/test/java/kr/codesquad/airbnb11/domain/room/RoomRepositoryTest.java
  BE/src/test/resources/application.yml
Labels: BE

#73 [BE #40] feat: reservation Mock Data 추가
  BE/src/main/resources/db/migration/V1.0.3__reservation_mock_data.sql
Labels: BE

#74 [BE #45] 검색결과에 요금 정보를 따로 전달하는 Mock API 생성
  BE/src/main/java/kr/codesquad/airbnb11/controller/RoomRestController.java
  BE/src/main/java/kr/codesquad/airbnb11/controller/response/RoomResponse.java
  BE/src/main/java/kr/codesquad/airbnb11/controller/response/SearchResponse.java
  BE/src/main/resources/application.yml
Labels: BE

#75 [BE #43,#45] 조회기능 추가
  BE/build.gradle
  BE/src/main/java/kr/codesquad/airbnb11/common/SQL.kt
  BE/src/main/java/kr/codesquad/airbnb11/controller/RoomRestController.java
  BE/src/main/java/kr/codesquad/airbnb11/controller/request/SearchRequest.java
  BE/src/main/java/kr/codesquad/airbnb11/controller/response/RoomResponse.java
  BE/src/main/java/kr/codesquad/airbnb11/controller/response/SearchResponse.java
  BE/src/main/java/kr/codesquad/airbnb11/domain/reservation/Reservation.java
  BE/src/main/java/kr/codesquad/airbnb11/domain/room/Room.java
  BE/src/main/java/kr/codesquad/airbnb11/domain/room/RoomDAO.java
Labels: BE

#78 [Deploy] 2020-05-29
  BE/build.gradle
  BE/src/main/java/kr/codesquad/airbnb11/common/SQL.kt
  BE/src/main/java/kr/codesquad/airbnb11/common/config/WebConfig.java
  BE/src/main/java/kr/codesquad/airbnb11/common/security/GithubKey.java
  BE/src/main/java/kr/codesquad/airbnb11/common/security/GithubPayload.java
  BE/src/main/java/kr/codesquad/airbnb11/common/security/GithubToken.java
  BE/src/main/java/kr/codesquad/airbnb11/common/security/GithubUser.java
  BE/src/main/java/kr/codesquad/airbnb11/common/utils/BigMoneyConverter.java
  BE/src/main/java/kr/codesquad/airbnb11/controller/LoginController.java
  BE/src/main/java/kr/codesquad/airbnb11/controller/RoomRestController.java
  BE/src/main/java/kr/codesquad/airbnb11/controller/request/SearchRequest.java
  BE/src/main/java/kr/codesquad/airbnb11/controller/response/RoomResponse.java
  BE/src/main/java/kr/codesquad/airbnb11/controller/response/SearchResponse.java
  BE/src/main/java/kr/codesquad/airbnb11/domain/reservation/Reservation.java
  BE/src/main/java/kr/codesquad/airbnb11/domain/room/Room.java
  BE/src/main/java/kr/codesquad/airbnb11/domain/room/RoomDAO.java
  BE/src/main/java/kr/codesquad/airbnb11/domain/room/RoomDTO.java
  BE/src/main/java/kr/codesquad/airbnb11/domain/user/User.java
  BE/src/main/java/kr/codesquad/airbnb11/domain/user/UserDTO.java
  BE/src/main/java/kr/codesquad/airbnb11/domain/user/UserRepository.java
  BE/src/main/java/kr/codesquad/airbnb11/service/JwtService.java
  BE/src/main/java/kr/codesquad/airbnb11/service/LoginService.java
  BE/src/main/java/kr/codesquad/airbnb11/service/OAuthService.java
  BE/src/main/java/kr/codesquad/airbnb11/service/dummy
  BE/src/main/resources/application.yml
  BE/src/main/resources/db/migration/V1.0.3__reservation_mock_data.sql
  BE/src/test/java/kr/codesquad/airbnb11/common/utils/BigMoneyConverterTest.java
  BE/src/test/java/kr/codesquad/airbnb11/domain/room/RoomDTOTest.java
  BE/src/test/java/kr/codesquad/airbnb11/domain/room/RoomRepositoryTest.java
  BE/src/test/resources/application.yml
Labels: BE

#79 [BE] review mock data, oauth 추가 수정
  BE/src/main/java/kr/codesquad/airbnb11/domain/user/UserDTO.java
  BE/src/main/java/kr/codesquad/airbnb11/service/LoginService.java
  BE/src/main/resources/db/migration/V1.0.4__review_mock_data.sql
Labels: BE

#80 Revert "[BE] review mock data, oauth 추가 수정"
  BE/src/main/java/kr/codesquad/airbnb11/domain/user/UserDTO.java
  BE/src/main/java/kr/codesquad/airbnb11/service/LoginService.java
  BE/src/main/resources/db/migration/V1.0.4__review_mock_data.sql
Labels: BE

#82 [BE #68] 예약 기능을 추가합니다.
  BE/src/main/java/kr/codesquad/airbnb11/controller/RoomRestController.java
  BE/src/main/java/kr/codesquad/airbnb11/controller/request/ReservationRequest.java
  BE/src/main/java/kr/codesquad/airbnb11/domain/reservation/Reservation.java
  BE/src/main/java/kr/codesquad/airbnb11/domain/reservation/ReservationRepository.java
  BE/src/main/resources/db/migration/V1.0.0__schema_init.sql
Labels: BE

#85 [FE] 불필요한 props, 하드코딩 되어있는 부분 수정
  FE/src/components/Common/DateButton/DateButton.jsx
  FE/src/components/Common/GuestButton/GuestButton.jsx
  FE/src/components/Main/Header/Header.jsx
  FE/src/components/Main/SearchNavigation/SearchNavigation.jsx
  FE/src/constants/mainpage.js
  FE/src/routers/AppRouter.jsx
Labels: FE

#86 [FE] modify: 로고 참조 수정
  FE/src/components/SearchResult/Header/Header.jsx
Labels: FE

#88 [BE #48] RoomRestController 테스트를 추가합니다.
  BE/src/main/java/kr/codesquad/airbnb11/common/config/WebConfig.java
  BE/src/main/java/kr/codesquad/airbnb11/controller/RoomRestController.java
  BE/src/main/java/kr/codesquad/airbnb11/controller/request/SearchRequest.java
  BE/src/main/java/kr/codesquad/airbnb11/service/RoomService.java
  BE/src/test/java/kr/codesquad/airbnb11/Airbnb11ApplicationTests.java
  BE/src/test/java/kr/codesquad/airbnb11/controller/RoomRestControllerTest.java
Labels: BE
